import Head from "next/head";
import Image from "next/image";
import HomeCard from "../components/HomeCard";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Monuments</h1>

        <p className={styles.description}>
          вироби з натурального граніту <br />
        </p>

        <div className={styles.grid}>
          <HomeCard
            img='/pamyatnik2.png'
            url='./pamyatnik'
            header='Памятники'
            paragraph="Гранітні надгробні пам'ятники різної складності"
          />

          <HomeCard
            img='/stupeni.png'
            url='./stupeni'
            header='Сходи з граніту'
            paragraph='Гранітні сходи - матеріал з найкращими властивостями'
          />

          <HomeCard
            img='/vaza.jpg'
            url='./vazy'
            header='Вази з граніту'
            paragraph='гранітні вази - красиве та функціональне доповнення дизайну'
          />
          <HomeCard
            img='/brukivka.jpg'
            url='./brukivka'
            header='Гранітна бруківка'
            paragraph='Бруківка з натурального каменю - гарне і надійне покриття'
          />
        </div>
        <p>
          Памятник з граніту - це скульптурна або архітектурна споруда, яка
          створена з природного матеріалу - граніту. Граніт - це мінералічна
          порода, яка складається з кристалів кварцу, слюди та фельдспату. Цей
          матеріал відомий своєю міцністю, твердістю, стійкістю до зношування та
          погодних умов, тому часто використовується для створення меморіальних
          та памятних споруд. Памятники з граніту можуть мати різну форму та
          розмір. Вони можуть бути високими та масивними, або ж невеликими та
          компактними. Зазвичай на поверхню памятників з граніту виконують
          різьблення, гравіювання або барельєфи, на яких зображені емблеми,
          символіка, написи або портрети вшануваної особи. Памятники з граніту
          можуть мати різні цілі та призначення, наприклад, вони можуть
          встановлюватись в память про померлих, вшанування видатних
          особистостей, як символ певної події або як частина архітектурного
          ансамблю.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
